# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0003_auto_20170727_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Python', max_length=100),
            preserve_default=False,
        ),
    ]
