# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0005_auto_20170801_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='A',
        ),
        migrations.RemoveField(
            model_name='question',
            name='B',
        ),
        migrations.RemoveField(
            model_name='question',
            name='C',
        ),
        migrations.RemoveField(
            model_name='question',
            name='D',
        ),
    ]
