# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0007_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
