# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0008_auto_20170802_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aptitude.Question'),
        ),
    ]
