# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0009_auto_20170802_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_time', models.DateTimeField(auto_now_add=True)),
                ('marks', models.IntegerField(default=0)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aptitude.Attendee')),
            ],
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
