# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0011_remove_result_test_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer',
        ),
    ]
