# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0012_auto_20170803_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
