# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitude', '0014_auto_20170803_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
    ]
